# Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
# By starting with 1 and 2, the first 10 terms will be:
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
# By considering the terms in the Fibonacci sequence whose values do not exceed
# four million, find the sum of the even-valued terms.

# o e o o e o o e
# Therefore add every 3rd fib number.
# Alternatively add every number except 3 fib number.
fib1 = 1
fib2 = 2
sumfib = 2
maxfib = 4000000
while True:
    fib3 = fib1 + fib2
    if fib3 > maxfib:
        break
    if not fib3 % 2:
        sumfib += fib3
    fib1 = fib2 + 0
    fib2 = fib3 + 0

print(sumfib)


