# Triangle, pentagonal, and hexagonal numbers are generated by the following formulae:

# Triangle	 	Tn=n(n+1)/2	 	1, 3, 6, 10, 15, ...
# Pentagonal	 	Pn=n(3n−1)/2	 	1, 5, 12, 22, 35, ...
# Hexagonal	 	Hn=n(2n−1)	 	1, 6, 15, 28, 45, ...
# It can be verified that T285 = P165 = H143 = 40755.

# Find the next triangle number that is also pentagonal and hexagonal.

import numpy as np
def is_pentagonal(n): return (1+np.sqrt(1+24*n))%6==0
def is_hexagonal(n): return (1+np.sqrt(1+8*n))%4==0
def is_triangle(n): return (-1+np.sqrt(1+8*n))%2==0

for n in range(286, 1000000):
    t = int(n*(n+1)/2)
    if is_pentagonal(t) and is_hexagonal(t):
        print(n, t)
        break
